%% PCA applied on Eating_in_UK.csv
warning off;clearvars; close all; clc;
%% Importing data
description = readtable('Eating_in_UK.csv'); % Import the dataset from a CSV
% In this case, the CSV table should be organize as the predictor by
% columns and id's or 'sample' by rows
disp(description) % Show the table for the user
labels = table2cell(description(:,1)); % The column of id's as a cell to label points in plot
data = importcsv('Eating_in_UK.csv'); % Uses an Auto-generated by MATLAB function to import
data_ = center_scale(data); % Function to Normalize the data - Zero Mean and Std Unitaire
%% PCA - Non Normalized
[~,score,latent] = pca(data); % Apply the PCA on non normalized data
disp('---------------') % Visual Separation
% Score - Non Normalized
disp('score: 1st column')
score(:,1) = -score(:,1)
disp('score: 2nd column')
score(:,2)
%% PCA Plot - Coefficients for Each Dimension (Scree Plot)
% https://faithfull.me/using-pca-when-there-are-less-samples-than-dimensions/
% This source provides the explanation about the number of
% A sample of size n with p dimensions has at most n?1 principal components if n?p.
figure
scatter(1:size(latent),latent,'filled');
hold on
plot(1:size(latent),latent,'Color','k');
set(gca,'Color','none')
set(gca, 'XTick', 1:size(latent))
hold off
title('ScreePlot')
xlabel('Components')
ylabel('Variance')
grid on
%% PCA Plot - 2D plan
figure
s1 = scatter(score(:,1),score(:,2),'filled');
set(gca,'Color','none')
s1.MarkerFaceColor = 'b';
text(score(:,1),score(:,2),labels,...
     'VerticalAlignment','bottom',...
     'HorizontalAlignment','center')
title('2D - Principals Components Plan')
xlabel('pc1')
ylabel('pc2')
grid on
%% PCA Plot - 1D plan
figure
hAxes = axes('NextPlot','add',...           % Add subsequent plots to the axes,
             'DataAspectRatio',[1 1 1],...  %   match the scaling of each axis,
             'YLim',[0 eps],...             %   set the y axis limit (tiny!),
             'Color','none');               %   and don't use a background color
plot(score(:,1),0,'b.','MarkerSize',24);
text(score(:,1),zeros(1,4),labels,...
     'VerticalAlignment','bottom',...
     'HorizontalAlignment','center')
title('1D - Principals Components Plan',... % Add a title
      'Position',[100, 1000*eps]) %
xlabel('pc1')
%% PCA - Normalized
[~,score_,latent_] = pca(data_); % Apply the PCA on non normalized data
disp('---------------') % Visual Separation
% Score - Non Normalized
disp('score: 1st column')
score(:,1) = -score(:,1)
disp('score: 2nd column')
score(:,2)
%% End
